import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import coverPlaylist from "@/assets/img/playListCover.png";
import { BsFillPlayFill, BsSearch, BsArrowDownCircle } from "react-icons/bs";
import { BiSolidDownArrow } from "react-icons/bi";
import { MdOutlinePersonAdd } from "react-icons/md";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.hero}>
          <div className={styles.heroImage}>
            <Image
              src={coverPlaylist}
              width={300}
              height={300}
              alt="Picture of the author"
            />
          </div>
          <div className={styles.heroText}>
            <h1>lofi for code and study 🌚</h1>
            <span>Music for focus when you code and study</span>
          </div>
        </div>
        <div className={styles.musicList}>
          <div className={styles.playListControl}>
            <div className={styles.playListControlLeft}>
              <BsFillPlayFill className={styles.playButton} />
              <button className={styles.outlineButton}>Enriquecer</button>
              <BsArrowDownCircle  className={styles.downloadButton}/>
              <MdOutlinePersonAdd  className={styles.addContributionUser}/>
            </div>
            <div className={styles.playListControlRight}>
              <BsSearch className={styles.searchButton} />
              <button className={styles.dropdownButton}>Ordem personalizada <BiSolidDownArrow className={styles.dropdownButtonIcon}/></button>
            </div>
          </div>
          <div className={styles.musicTable}></div>
        </div>
      </main>
    </>
  );
}
