import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import coverPlaylist from "@/assets/img/playListCover.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.hero}>
          <div className={styles.heroImage}>
            <Image
              src={coverPlaylist}
              width={300}
              height={300}
              alt="Picture of the author"
            />
          </div>
          <div className={styles.heroText}>
            <h1>lofi for code and study 🌚</h1>
            <span>Music for focus when you code and study</span>
          </div>
        </div>
        <div className={styles.musicList}></div>
      </main>
    </>
  );
}
